version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "8083:27017"
    volumes:
      - /root/aipo/BD/data:/BD/data
  aipo:
    build: .
    volumes:
      - /root/aipo:/aipo
    depends_on:
      - mongo



