version: "3.8"
services:
  main:
    build: .
    volumes:
      - .:.
    links:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    volumes:
      - database:data/db


volumes:
  database: