version: "3.8"
services:
  aipo:
    build: .
    volumes:
      - /root/aipo:/aipo
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "8083:8092"
    volumes:
      - /root/aipo/BD/data:/BD/data

