version: "3.8"
services:
  aipo:
    build: .
    volumes:
      - .:.
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - database:/data/db


volumes:
  database: